remote_theme: rayanfam/just-the-docs

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/hyperdbg.png"

# Aux links for the upper right navigation
aux_links:
  "HyperDbg":
    - "//hyperdbg.org"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
